<?php

return [
    'title' => 'Reports', 'description' => 'Analyse fleet activity, vehicle use and reported events.', 'summary' => 'Fleet overview', 'trips' => 'Trips and stops', 'usage' => 'Vehicle utilisation', 'safety' => 'Safety',
    'period' => 'Period', 'today' => 'Today', 'yesterday' => 'Yesterday', 'week' => 'Last 7 days', 'month' => 'Last 30 days', 'custom' => 'Custom', 'from' => 'From', 'to' => 'To', 'fleet' => 'Fleet', 'department' => 'Department', 'vehicles' => 'Vehicles', 'all_fleets' => 'All fleets', 'all_departments' => 'All departments', 'all_vehicles' => 'All vehicles in this filter', 'selected' => ':count vehicle(s) selected', 'find_vehicle' => 'Search vehicles…',
    'generate' => 'Generate report', 'restore' => 'Restore defaults', 'preset' => 'My templates', 'choose_preset' => 'Choose a template', 'preset_name' => 'Template name', 'save_preset' => 'Save template', 'delete_preset' => 'Delete', 'preset_saved' => 'Template saved. Dates will be recalculated each time it is used.', 'preset_deleted' => 'Template deleted.', 'preset_hint' => 'Templates save filters and period length, not results.',
    'initial' => 'Choose a period and generate a report.', 'queued' => 'Report queued…', 'running' => 'Analysing received readings…', 'ready' => 'Report ready', 'failed' => 'The report could not be prepared. Please retry.', 'busy' => 'Two reports are already being prepared. Please wait.', 'loading' => 'Loading…', 'changed' => 'Filters changed: generate a report to update the results.', 'limit_days' => 'Choose a period of up to 31 days.', 'limit_vehicles' => 'Select up to 100 vehicles.', 'no_vehicles' => 'No accessible vehicles match these filters.', 'too_large' => 'Too many readings. Select a shorter period or fewer vehicles.', 'scope_changed' => 'Assignments or permissions have changed. Generate a new report.', 'expired' => 'This report has expired. Generate it again.', 'not_ready' => 'The report is still being prepared.', 'invalid_sort' => 'This sort is unavailable.', 'preset_limit' => 'You can save up to 20 templates.',
    'distance' => 'Estimated GPS distance', 'moving' => 'Time in motion', 'alerts' => 'Reported alarms', 'coverage' => 'Documented period', 'comparison' => 'Previous period', 'insufficient' => 'Comparison unavailable: insufficient data.', 'comparison_hint' => 'Same duration in the preceding period. Changes may also reflect different data coverage.', 'quality' => 'Data quality', 'method' => 'Distances are estimated between valid GPS points. A trip requires at least 1 minute, 100 m travelled and a 50 m GPS extent; unconfirmed movement remains unknown. Gaps over 5 minutes, invalid positions and implausible jumps remain unknown. Listed stops last at least 3 minutes; brief ignition-on stops may be included in a trip. ACC does not prove the engine is running. Times use Kinshasa.', 'quality_hint' => ':known documented · :unknown missing or uncertain, summed across the selected vehicles. Trip boundaries are observed readings, not necessarily the actual departure and arrival.', 'safety_hint' => 'Alarms reported by cameras: a sustained alarm is only counted on onset. No alarm does not prove no incident occurred. No driver score or ADAS/DMS detection is inferred.',
    'daily' => 'Daily activity', 'daily_hint' => 'Days with no data must not be interpreted as days without activity.', 'results' => 'Detailed results', 'search' => 'Search results…', 'show' => 'Show', 'actions' => 'Actions', 'empty' => 'No results for this selection.', 'pagination' => 'Showing :from to :to of :total', 'previous' => 'Previous', 'next' => 'Next', 'pdf' => 'Export PDF', 'excel' => 'Export Excel', 'exporting' => 'Preparing file…', 'export_failed' => 'The file could not be created. Please retry.', 'generated' => 'Generated on', 'expires_hint' => 'Results remain available for 24 hours. Templates are retained.', 'map' => 'View trip', 'position' => 'View position', 'recordings' => 'Recordings', 'detail' => 'Report context', 'close' => 'Close', 'map_unavailable' => 'The map could not be loaded. Try again from Map.', 'recordings_hint' => 'The vehicle and date are selected in Recordings. Click Search to query the memory card.', 'recordings_busy' => 'A recording transfer is in progress. Finish it before changing vehicles.',
    'state_moving' => 'Trip', 'state_stopped' => 'Stop · ignition on', 'state_parking' => 'Parking · ignition off', 'quality_no_data' => 'Insufficient data', 'quality_incomplete' => 'Incomplete period', 'quality_observed' => 'Documented period', 'col_vehicle' => 'Vehicle', 'col_fleet' => 'Fleet', 'col_distance_km' => 'Estimated distance', 'col_moving_seconds' => 'In motion', 'col_trips' => 'Trips', 'col_alerts' => 'Alarms', 'col_coverage' => 'Coverage', 'col_quality_label' => 'Data', 'col_state_label' => 'Activity', 'col_start' => 'Observed start', 'col_end' => 'Observed end', 'col_duration_seconds' => 'Observed duration', 'col_max_speed' => 'Max. speed', 'col_active_days' => 'Days in motion', 'col_stopped_seconds' => 'Stopped · ACC on', 'col_parking_seconds' => 'Parked · ACC off', 'col_unknown_seconds' => 'Without data', 'col_at' => 'Date and time', 'col_alarm_label' => 'Alarm', 'col_speed' => 'Speed', 'col_position_label' => 'GPS position',
    'alarm_0' => 'SOS', 'alarm_1' => 'Overspeed', 'alarm_2' => 'Fatigue', 'alarm_4' => 'GPS fault', 'alarm_5' => 'GPS antenna disconnected', 'alarm_6' => 'GPS antenna fault', 'alarm_7' => 'Low battery', 'alarm_8' => 'Power cut', 'alarm_9' => 'Display fault', 'alarm_10' => 'Audio fault', 'alarm_11' => 'Camera fault', 'alarm_29' => 'Collision', 'alarm_30' => 'Rollover', 'alarm_other' => 'Other terminal alarm',
];
