<?php

return [
    'title' => 'Rapports', 'description' => 'Analysez l’activité, l’utilisation et les événements de votre flotte.',
    'summary' => 'Synthèse de flotte', 'trips' => 'Trajets et arrêts', 'usage' => 'Utilisation des véhicules', 'safety' => 'Sécurité',
    'period' => 'Période', 'today' => 'Aujourd’hui', 'yesterday' => 'Hier', 'week' => '7 derniers jours', 'month' => '30 derniers jours', 'custom' => 'Personnalisée',
    'from' => 'Du', 'to' => 'Au', 'fleet' => 'Flotte', 'department' => 'Département', 'vehicles' => 'Véhicules', 'all_fleets' => 'Toutes les flottes', 'all_departments' => 'Tous les départements', 'all_vehicles' => 'Tous les véhicules du filtre', 'selected' => ':count véhicule(s) sélectionné(s)', 'find_vehicle' => 'Rechercher un véhicule…',
    'generate' => 'Générer le rapport', 'restore' => 'Restaurer par défaut', 'preset' => 'Mes modèles', 'choose_preset' => 'Choisir un modèle', 'preset_name' => 'Nom du modèle', 'save_preset' => 'Enregistrer le modèle', 'delete_preset' => 'Supprimer', 'preset_saved' => 'Modèle enregistré. La période sera recalculée à chaque utilisation.', 'preset_deleted' => 'Modèle supprimé.', 'preset_hint' => 'Un modèle conserve les filtres et la durée de la période, pas les résultats.',
    'initial' => 'Choisissez votre période et générez un rapport.', 'queued' => 'Rapport en attente de calcul…', 'running' => 'Analyse des relevés en cours…', 'ready' => 'Rapport prêt', 'failed' => 'Le rapport n’a pas pu être préparé. Réessayez.', 'busy' => 'Deux rapports sont déjà en préparation. Patientez avant de relancer.', 'loading' => 'Chargement…', 'changed' => 'Filtres modifiés : générez un rapport pour actualiser les résultats.',
    'limit_days' => 'Choisissez une période de 31 jours maximum.', 'limit_vehicles' => 'Sélectionnez au maximum 100 véhicules.', 'no_vehicles' => 'Aucun véhicule accessible pour ces filtres.', 'too_large' => 'Cette sélection contient trop de relevés. Réduisez la période ou le nombre de véhicules.', 'scope_changed' => 'Les affectations ou les autorisations ont changé. Générez un nouveau rapport.', 'expired' => 'Ce rapport a expiré. Générez-le à nouveau.', 'not_ready' => 'Le rapport est encore en préparation.', 'invalid_sort' => 'Ce tri n’est pas disponible.', 'preset_limit' => 'Vous pouvez conserver au maximum 20 modèles.',
    'distance' => 'Distance GPS estimée', 'moving' => 'Temps en mouvement', 'alerts' => 'Alarmes reçues', 'coverage' => 'Période documentée', 'comparison' => 'Période précédente', 'insufficient' => 'Comparaison indisponible : données insuffisantes.', 'comparison_hint' => 'Même durée sur la période précédente. Les écarts peuvent aussi refléter une différence de données reçues.', 'quality' => 'Fiabilité des données',
    'method' => 'Distances estimées entre positions GPS valides. Un trajet demande au moins 1 minute, 100 m parcourus et une étendue GPS de 50 m ; les mouvements non confirmés restent incertains. Un intervalle de plus de 5 minutes, une position invalide ou un saut incohérent reste sans données. Les arrêts affichés durent au moins 3 minutes ; les pauses courtes avec contact allumé peuvent appartenir au même trajet. Le contact ACC ne prouve pas que le moteur tourne. Les horaires suivent Kinshasa.',
    'quality_hint' => ':known documentées · :unknown sans données ou incertaines, cumulées sur les véhicules de la sélection. Les limites d’un trajet sont celles des relevés disponibles, pas nécessairement son départ et son arrivée réels.',
    'safety_hint' => 'Alarmes signalées par les caméras : une alarme maintenue n’est comptée qu’à son apparition. L’absence d’alarme ne prouve pas l’absence d’incident. Aucun score de conducteur ni détection ADAS/DMS n’est déduit de ces données.',
    'daily' => 'Activité quotidienne', 'daily_hint' => 'Les jours sans données ne doivent pas être interprétés comme des jours sans activité.', 'results' => 'Résultats détaillés', 'search' => 'Rechercher dans les résultats…', 'show' => 'Afficher', 'actions' => 'Actions', 'empty' => 'Aucun résultat pour cette sélection.', 'pagination' => 'Affichage de :from à :to sur :total', 'previous' => 'Précédent', 'next' => 'Suivant', 'pdf' => 'Exporter PDF', 'excel' => 'Exporter Excel', 'exporting' => 'Préparation du fichier…', 'export_failed' => 'Impossible de créer le fichier. Réessayez.', 'generated' => 'Généré le', 'expires_hint' => 'Résultats disponibles pendant 24 h. Les modèles sont conservés.', 'map' => 'Voir le trajet', 'position' => 'Voir la position', 'recordings' => 'Enregistrements', 'detail' => 'Contexte du rapport', 'close' => 'Fermer', 'map_unavailable' => 'La carte ne peut pas être chargée. Réessayez depuis la rubrique Carte.', 'recordings_hint' => 'La date et le véhicule ont été sélectionnés dans Enregistrements. Cliquez sur Rechercher pour interroger la carte mémoire.', 'recordings_busy' => 'Un transfert est en cours dans Enregistrements. Terminez-le avant de changer de véhicule.',
    'state_moving' => 'Trajet', 'state_stopped' => 'Arrêt · contact allumé', 'state_parking' => 'Stationnement · contact éteint', 'quality_no_data' => 'Sans données suffisantes', 'quality_incomplete' => 'Période incomplète', 'quality_observed' => 'Période documentée',
    'col_vehicle' => 'Véhicule', 'col_fleet' => 'Flotte', 'col_distance_km' => 'Distance estimée', 'col_moving_seconds' => 'En mouvement', 'col_trips' => 'Trajets', 'col_alerts' => 'Alarmes', 'col_coverage' => 'Couverture', 'col_quality_label' => 'Données', 'col_state_label' => 'Activité', 'col_start' => 'Début observé', 'col_end' => 'Fin observée', 'col_duration_seconds' => 'Durée observée', 'col_max_speed' => 'Vitesse max.', 'col_active_days' => 'Jours en mouvement', 'col_stopped_seconds' => 'Arrêt · ACC allumé', 'col_parking_seconds' => 'Stationnement · ACC éteint', 'col_unknown_seconds' => 'Sans données', 'col_at' => 'Date et heure', 'col_alarm_label' => 'Alarme', 'col_speed' => 'Vitesse', 'col_position_label' => 'Position GPS',
    'alarm_0' => 'SOS', 'alarm_1' => 'Excès de vitesse', 'alarm_2' => 'Fatigue', 'alarm_4' => 'Défaut GPS', 'alarm_5' => 'Antenne GPS débranchée', 'alarm_6' => 'Défaut antenne GPS', 'alarm_7' => 'Batterie faible', 'alarm_8' => 'Alimentation coupée', 'alarm_9' => 'Défaut écran', 'alarm_10' => 'Défaut audio', 'alarm_11' => 'Défaut caméra', 'alarm_29' => 'Collision', 'alarm_30' => 'Retournement', 'alarm_other' => 'Autre alarme terminal',
];
