Listen 127.0.0.1:8081
<VirtualHost 127.0.0.1:8081>
    ServerName exadcam-internal
    DocumentRoot /var/www/exadcam/public
    DirectoryIndex index.php
    <Directory /var/www/exadcam/public>
        Options -Indexes -MultiViews +FollowSymLinks
        AllowOverride All
        Require local
    </Directory>
    <Location />
        Require local
    </Location>
    ErrorLog /var/log/apache2/exadcam-internal-error.log
</VirtualHost>
